#+TITLE: Personal Notes
* Binary Trees
** Global Variable
I need to get better at using global variables. Take the following java code that constructs a tree from a preorder traversal for example:
#+BEGIN_SRC java
class ConstructTree {
    // This is a global variable we are going to use to keep track of our position in the list to create our preorder tree.
    public static int globalIndex;

    public static constructTreeFromPreorder(List<Integer> preorder) {
        if(preorder == null) {
            return null;
        }

        globalIndex = 0;
        return constructer(preorder, Integer.MIN_VALUE, Integer.MAX_VALUE);
    }

    private static constructer(List<Integer> preorder, Integer lowerBound, Integer upperBound) {
        // If the global index is at the end of the array we have finished constructing the tree and can return null.
        if(globalIndex == preorder.size() || preorder[globalIndex] < lowerBound || preorder[globalIndex] > upperBound) {
            return null;
        }

        // In a preorder traversal, the element at globalIndex is the root of a subtree. Since a preorder traversal travels down the left subtree first construct the left subtree first.
        TreeNode root = new TreeNode(preorder.get(globalIndex++));
        // We adjust the boundaries for the tree depending on the root.
        root.left = constructer(preorder, lowerBound, root.val);
        root.right = constructer(preorder, root.val, upperBound);
        return root;
    }
}
#+END_SRC
We used a global variable to avoid using a linear scan at every recursive level which would lead to a polynomial time complexity. Another example of using a global variable is checking if a tree is height balanced.

#+BEGIN_SRC java
class BalancedTree {
    // Our boolean global variable that tells us if the tree is balanced
    public static boolean isBalanced;

    public static boolean isTreeBalanced(TreeNode root) {
        // We set the global variable to true when we call the function
        isBalanced = true;
        getHeight(root);
        // Return isBalanced. The state of this variable will be updated if the height is unbalanced by the getHeight function.
        return isBalanced;
    }

    public static int getHeight(TreeNode root) {
        if(root == null) {
            return 0;
        }

        int leftSize = getHeight(root.left);
        int rightSize = getHeight(root.right);
        // If the absolute difference between the size of the left subtree and the size of the right subtree is greater than 1 then set the global isBalanced to false.
        if(Math.abs(leftSize - rightSize) > 1) {
            isBalanced = false;
        }

        return Math.max(leftSize, rightSize) + 1;
    }
}
#+END_SRC
** Understanding What the Root Represents(BST)
There are certain questions where I get confused/stuck because I was unable to identify all given information I had. In a BST identifying the root means two things.

1. Obviously we have the root which is good.
2. More significantly we have the upper bound for the left subtree and the lower bound for the right subtree.

Generally if I am able to identify the root I have found some important information. Whether it be boundaries for subtrees or a base case for recursion, I should spend more time identifying the given information I have.

An example of what the root represents:
#+BEGIN_SRC java
public TreeNode constructTreeFromPreorderInorder(int[] inorder, int[] preorder) {
    return helper(preorder, 0, preorder.length, 0, inorder.length, IntStream(0, inorder.length).boxed()
                  .collect(Collectors.toMap(i -> inorder[i], i -> i)));
}

private TreeNode helper(int[] preorder, int pStart, int pEnd, int iStart, int iEnd, Map<Integer, Integer> inorderIdx) {
    if(pStart >= pEnd || iStart >= iEnd) {
        return null;
    }

    // We can find the root of the tree because the first element in the preorder sequence is the root of the tree.
    TreeNode root = new TreeNode(preorder.get(pStart));
    // So what are the implications of knowing the root?
    // Well we can find where the root is in the inorder sequence. All elements left of the root in the inorder sequence are elements that belong to the left subtree. The opposing logic applies in that all elements right of the root are elements that belong to the right subtree.
    // Because we know where the index of the root is, we can find the size of the left subtree. This is all the information we need. We know that the left subtree of the root is going to consist of all the elements from pstart + 1 to the size of the left subtree and all elements from iStart to the index of the root in I.
    int inorderRootIdx = inorderIdx.get(root.val);
    int leftSubTreeSize = inorderIdx - iStart;

    root.left = helper(preorder, pStart + 1, pStart + 1 + leftSubTreeSize, iStart, inorderRootIdx, inorderIdx);
    root.right = helper(preorder, pStart + 1 + leftSubTreeSize, pEnd, inorderIdx + 1, iEnd, inorderIdx);
    return root;
}
#+END_SRC
Another example is validating a binary tree:
#+BEGIN_SRC java
public boolean validateTree(TreeNode root) {
    return helper(root, null, null);
}

private boolean helper(TreeNode root, Integer lowerBound, Integer upperBound) {
    // An empty binary tree is still a valid binary search tree
    if(root == null) {
        return true;
    }

    // The root of a particular tree is the upeer bound for its left subtree
    if(lowerBound != null && root.val <= lowerBound) return false;

    // The root of a particular tree is the lower bounder for its right subtree.
    if(upperBound != null && root.val >= upperBound) return false;

    // If the root's value lies in between the bounds then we need to recursively check its left and right subtrees to see if they are valid.
    boolean left = helper(root.left, lowerBound, root.val);
    boolean right = helper(root.right, root.val, upperBound);
    // If both the left and right subtrees are valid that means that we have successfully validated the binary tree.
    return (left && right) ? true : false;
}
#+END_SRC
**  Traversals
I need to better understand traversal algorithms. They are easy to memorize, but it is difficult to understand the applications/manipulation of the traversals.

Take the inorder traversal for instance. The inorder traversal is a depth first traversal that visits the left leaves of the tree first before recursing upwards and and to the right child. It's recursive algorithm is easy to memorize:
#+BEGIN_SRC java
public void inorder(TreeNode root) {
    if(root != null) {
        inorder(root.left);
        System.out.println(root.val);
        inorder(root.right);
    }
}
#+END_SRC

Perhaps I need to find the leaves of a tree in right to left order. I could use a standard inorder traversal and then push the leaves into a stack and print the contents of the stack. However this would be both a waste of space and time. Instead we could just modify the inorder traversal such that we start from the right most leaf instead of the left most leaf.

Why would we want to perform a RL Inorder traversal? Well maybe a certain question calls for it. Let's say we are given the root of a binary search tree with distinct values and we are asked to modify it such that every node has a new value equal to the sum of the values of the original tree that are greater than or equal to node.val.

When looking at the problem you will come to the realization that the starting case for this problem is the right most leaf. This right most leaf will be incorporated into every sum. Working off that realization we can perform a RL inorder traversal while keeping track of the current sum in a global variable so that we know what the sum of all nodes to the right are so far.

#+BEGIN_SRC java
public class Solution {
    public int sumSoFar = 0;
    public TreeNode bstToGst(TreeNode root) {
        if(root != null) {
            bstToGst(root.right);
            sumSoFar += root.val;
            root.val += sumSoFar;
            bstToGst(root.left);
        }
        return root;
    }
}
#+END_SRC
